### ISSUE TITLE
Need example on how to exclude a polyfill from the modern bundle

### ISSUE THREAD

**Issue by platosha** [DanielSchaffer/webpack-babel-multi-target-plugin#11]
Some DOM APIs are present in all browsers that support ES modules, while could be absent in others, e. g., `URLSearchParams` and `fetch`. When I use polyfills for such APIs in my app, I want to exclude them from the modern bundle to save on the size.

Babel env does not help, because Babel does not care about the DOM APIs, it only polyfills the JS features themselves.

From README I cannot figure out, what could be done for this use case, if anything at all. The target-specific options seem not to mention anything related.

As a workaround, I add a separate entrypoint for `polyfills.js` in webpack, skip it in the HTML plugin and add only the legacy `polyfills.js` right in the HTML template file instead. This approach works, but could be improved in some ways:
- I have the `polyfills.modern.js` file built, but never used
- I wish I could include the polyfills in the main legacy bundle itself, rather than having the separate bundle.

**Comment by DanielSchaffer** [comment]
@platosha Unfortunately, I don't think there's an easy way to do this just through the plugin as it stands.

I think what I _could_ do is add a setting in the targeting options to explicitly allow or ignore specific entries for a given browser target. That way, if folks have a set of polyfills already set up, they can continue using it without impacting the modern bundle.

I'm imagining it'd look something like this:

```
module.exports = {
  entry: {
    main: './src/main.ts',
    polyfills: './src/polyfills.ts',
  },

  // loaders, etc

  plugins: [
    new BabelMultiTargetPlugin({
      targets: {
        modern: {
          entries: {
            exclude: ['polyfills'],
          },
        },
      },
    }),
  ],
}
```

If you'd prefer to have it all in one bundle/entry, there might also be a way to exclude specific modules using a similar setting, but I'd have to do a little more poking in the webpack internals to figure out how to do that.

Thoughts?

**Comment by platosha** [comment]
@DanielSchaffer Excluding entry points for the specific target would be an improvement for sure.

Speaking about having a single entry point, what could help, I think, is being able to configure a global const with [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) in a target-specific way, so that there is a global constant indicating the target at compile time. E. g., so that having something like this in webpack config:

```javascript
new BabelMultiTargetPlugin({
  targets: {
    modern: {
      define: {'TARGET': '"modern"'}
    }
  }
});
```

I could do this in my main.js:

```javascript
if (TARGET !== '"modern"') {
  require('./polyfills.js');
}
```

The DefinePlugin replacements are compile time, and it seems that webpack does not include this depencency in the bundle when the `if` expression is false.

**Comment by DanielSchaffer** [comment]
There are definitely ways I can programmatically add modules into a bundle - and I'd prefer to have the plugin do that over making users put conditionals like that in their code. Something like this:

```
module.exports = {
  entry: {
    main: './src/main.ts',
    polyfills: './src/polyfills.ts',
  },

  // loaders, etc

  plugins: [
    new BabelMultiTargetPlugin({
      targets: {
        legacy: {
          additionalModules: [
            'whatwg-fetch',
            'url-search-params-polyfill',
          ],
        },
      },
    }),
  ],
}
```

Do you mind listing which DOM API polyfills you're using so I can make sure whatever I add works with them?

As a side note - it'd be cool to have some sort of implementation that took a `browserslist` value, a list of DOM APIs, and gave you a list of polyfills needed.

**Comment by platosha** [comment]
Agree, the `additionalModules` approach is more straightforward, and seems more reliable over defines plus conditional inclusions.

Right now I’m using `URLSearchParams`, `fetch`, and `AbortController` polyfills, here is my [polyfills.js entrypoint](https://github.com/vaadin/base-starter-connect/blob/aae3e5c1cfdeff5520858d19918b287acec98c2c/frontend/polyfills.js):
```js
import URLSearchParams from 'url-search-params';
window.URLSearchParams = URLSearchParams;

import 'unfetch/polyfill/index.js';
import 'abortcontroller-polyfill/dist/polyfill-patch-fetch.js';
```

Maintaining the order of inclusion is important, the `AbortController` polyfill depends on the `fetch` one.

**Comment by DanielSchaffer** [comment]
@platosha 
**PR:** #16
**Prerelease:** [2.1.0-alpha.8](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.1.0-alpha.8)
