### ISSUE TITLE
Error when using with html-webpack-include-assets-plugin

### ISSUE THREAD

**Issue by platosha** [DanielSchaffer/webpack-babel-multi-target-plugin#14]
While using `webpack-babel-multi-target-plugin`, I also want webpack to append a script into `index.html`, which is not being compiled with webpack here, but copied from elsewhere. For that, I append `html-webpack-include-assets-plugin` in my webpack configuration like this:

```javascript
module.exports = {
  /* ... */,
  plugins: [
    new BabelMultiTargetPlugin(/*...*/),
    new HtmlWebpackPlugin({template: 'index.html'}),
    new HtmlWebpackIncludeAssetsPlugin({
      assets: ['copied_script.js'],
      append: true
    })
  ]
};
```

I’ve got this error when running `webpack`:

```
ERROR in   TypeError: Cannot read property 'map' of undefined

  - babel.multi.target.html.updater.js:30 tags.forEach
    [project]/[webpack-babel-multi-target-plugin]/src/babel.multi.target.html.updater.js:30:44
```

Thrown from these lines in `babel.multi.target.html.updater.js`:
```
            const targetedChunks = chunkMap.get(tag.attributes.src);
            const targets = targetedChunks.map(targetedChunk => targetedChunk.target);
            if (!targets || !targets.length) {
                return;
            }
 ```

The reason is that `html-webpack-include-assets-plugin` appends a script `tag` for the `copied_script.js`, which is not emitted from any entrypoint, and therefore not found in the `chunkMap`, so the `targetedChunks` const is undefined for this case.

**Comment by DanielSchaffer** [comment]
@platosha 
**PR:** #15 
**Prerelease:** [2.1.0-alpha.7](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.1.0-alpha.7)
