### ISSUE TITLE
[Discussion] Any thoughts about generates the true es6 ( aka not flattened ) modules?

### ISSUE THREAD

**Issue by CarterLi** [DanielSchaffer/webpack-babel-multi-target-plugin#29]
Great project! But I'm thinking further: What about generates unflattened modules?

1. Parse the whole repo recursively, to build an [import-map](https://github.com/WICG/import-maps). Or transform `import Xxx from 'some_module'` into `import Xxx from '/node_modules/some_module/index.js'`.
1. All files imported are still transformed using loaders specified by webpack configuration rules, with optional `.js` extension suffix. For example `a.scss` can be compiled into file `a.scss.js`, with its content  
```document.head.insertAdjacentHTML("beforeEnd", `<style>Generated CSS text</style>`);```
1. Commonjs [require](http://www.commonjs.org/specs/modules/1.0/) is compiled into synced XHR  
```js
// Pseudo code
function require(id) {
  const moduleId = getAbsolutePathSomehow(id);

  if (installedModules[moduleId]) {
    return resolvedModules[moduleId].exports;
  }

  const req = new XMLHttpRequest();
  req.open("GET", moduleId, false);
  req.send();
  const module = require.installedModules[moduleId] = {
    id: moduleId,
    loaded: false,
    exports: {},
  };
  new Function('module', 'exports', 'use strict;\n' + req.responseText)
    .call(module.exports, module, module.exports);
  module.loaded = true;
  return module.exports;
}
require.installedModules = {};

globalThis.require = require;
```

Another option is compiling commonjs module into ES6 default-export module.

Related issue: https://github.com/webpack/webpack/issues/8010#issuecomment-420122872

**Comment by DanielSchaffer** [comment]
@CarterLi - I agree, being able to use Webpack for outputting unflattened ES6 files would be great - but that's 100% to do with Webpack, and not this plugin.
