### ISSUE TITLE
presets for babel

### ISSUE THREAD

**Issue by barroudjo** [DanielSchaffer/webpack-babel-multi-target-plugin#54]
Since this plugin requires us to stop using babelrc (and I assume babel.config.js), how can we list additionnal presets to be used (such as @babel/typescript, @babel/preset-react ?

Thanks !

**Comment by DanielSchaffer** [comment]
@barroudjo You know, I think that might've been an oversight on my part - there's a way to add more plugins, and a way to customize the config for `preset-env`, but no way to add more presets.

I'll have to release a patch to add that to the plugin config. I'll try and get to that this week!

**Comment by barroudjo** [comment]
Thanks a lot, that would be great !

**Comment by barroudjo** [comment]
Did you have a chance to take a look at that patch ?
