### ISSUE TITLE
fork-ts-checker emits error

### ISSUE THREAD

**Issue by Austaras** [DanielSchaffer/webpack-babel-multi-target-plugin#58]
[bug reproduction repo](https://github.com/Austaras/boilerplate/tree/repro)

when use this plugin and fork-ts-checker together, fork-ts-checker will complain about
```
ERROR in /home/chla/Code/template/node_modules/webpack-babel-multi-target-plugin/dist/src/defaults.d.ts(1,36):
TS7016: Could not find a declaration file for module 'babel-loader'. '/home/chla/Code/template/node_modules/babel-loader/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/babel-loader` if it exists or add a new declaration (.d.ts) file containing `declare module 'babel-loader';`
```
which should be resolved by add your custom babel-loader typing to build result

**Comment by Austaras** [comment]
https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build

so it's TSC's fault, guess I should make fork-ts-checker to ignore it.

**Comment by DanielSchaffer** [comment]
This might be a packaging issue on my part - there's no reason a client project should have to worry about types for `babel-loader`. Those are only really used for development anyhow.

**Comment by Austaras** [comment]
After upgrade to fork-ts-checker@5, this issue is resolved
