### ISSUE TITLE
v2.5.0

### ISSUE THREAD

**Issue by DanielSchaffer** [DanielSchaffer/webpack-babel-multi-target-plugin#64]
@Austaras @despian @semoal @erezvish

Hey folks!

My apologies (again, as ever) for the delay in following up . You all have PRs or otherwise interest in the upcoming `2.5.0` release. I've just published a new prerelease, [v2.5.0-next.2](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.5.0-next.2), which includes the following PRs:

- #55 - support htmlwebpack v4
- #59 - add preset configuration to babel options
- #62 - add exclude for 'querystring-es3'
- #63 - add inject (head|body) and minify options to safari10NoModuleFix

Please take a few moments to make sure everything is working as intended, and once I hear back from everyone I'll do the final release.

Thanks again for all of your contributions, I truly appreciate the help!

**Comment by Austaras** [comment]
everything works fine for me, I'm trying to figure out how to fix my other two issue.

**Comment by DanielSchaffer** [comment]
Oh, I'd meant to also say that for #60, I'm planning on a major release (3.0) after 2.5.0 goes out since corejs is a pretty integral part of how this plugin works, and the default is changing by a major version.

**Comment by moderndeveloperllc** [comment]
I would probably up the `html-webpack-plugin` `peerDependency` to be 4.0.0 (without the beta) as it's now up to 4.0.1. Some projects might not like the beta dependency.

**Comment by DreierF** [comment]
What about #56 respectively #65? Could this go into a 2.5.1?

**Comment by Austaras** [comment]
@DreierF that pr is only meant to be a temporary workaround and make 2.5.0 usable for me. Someone, maybe me, should figure out a proper fix in the long run.

**Comment by erezvish** [comment]
Hi
I'll try to get around to it soon but no promises.
With the covid-19 craziness getting things done is a bit difficult right now

**Comment by moderndeveloperllc** [comment]
@DanielSchaffer Are you still looking to add the `options.loaderOptions` and deprecation warnings (#36, #37) before 2.5, or wait on that?

**Comment by DanielSchaffer** [comment]
@moderndeveloperllc Hi! My only concern is that there's a 2.x release that deprecates the things that will be removed before they actually get removed in 3.0. Unfortunately, I haven't had much time to focus on this project lately, so can't say when I'll be able to do either of those things.

**Comment by DanielSchaffer** [comment]
Apologies for the long delay on this folks. I'm sure you all understand it's been a long crazy couple of months. Anyhow, here's [2.5.0](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.5.0) 🍻

I've started a 2.6.0 milestone for the deprecation tasks / 3.x prep mentioned above.
